GET  http://localhost:3001/persons/

###
DELETE http://localhost:3001/persons/

###
POST  http://localhost:3001/persons/
content-type: application/json

   

{   
    "name": "adding data in database",
    "number": 2389700809
}